app/services/settings_service/repository_base.rb

[PLAY-901](https://strongmind.atlassian.net/browse/PLAY-901)
- Used env var for AWS Region in settings service instead of hardcoded string

[PLAY-901] Changed settings service to user env variable for AWS region

---

app/decorators/models/user_decorator.rb

I am unable to test this in my current environment, so this may be horribly wrong. But I think this will help with some of the scenarios around users getting lost after they are created. This does depend on a bug fix being deployed in Identity (https://dev.azure.com/strongmind/Strongmind/_git/Identity/pullrequest/6942)

Add return URL back to Canvas on reset email

---

app/decorators/models/context_module_progression_decorator.rb
spec/models/context_module_progression_spec.rb

This commit also includes a new test to ensure that the course_progress nound indeed get published.
Closes STEAK-725

Behavioral: STEAK-725: added the course_progress noun publishing back

---

app/decorators/models/delayed/job.rb

Co-authored-by: Angel Diaz <angel.diaz@strongmind.com>
Co-authored-by: Charles Parisi <charles.parisi@strongmind.com>
Co-authored-by: Christopher Adeszko <christopher.adeszko@strongmind.com>

QTY-362 truncate source in delayed jobs before save if length exceeds limit

---

app/assets/javascripts/canvas_shim/application.js.erb

[QTY-1413](https://strongmind.atlassian.net/browse/QTY-1413)
#Delete comments under headings and replace with appropriate descriptions for each category
downgrade ruby from 2.6.10 to 2.5, there were more incompatibilities found on thursday with ruby 2.6.
downrade using deps and gemfile
We rolled out this image thursday night.

QTY-1414: downgrade ruby back down to 2.5

---

app/services/assignments_service/scheduler.rb
app/views/accounts/settings.html.erb
spec/services/assignments_service/commands/distribute_due_dates_spec.rb
spec/services/assignments_service/commands/set_enrollment_assignment_due_dates_spec.rb
spec/services/assignments_service/scheduler_spec.rb

[QTY-1331](https://strongmind.atlassian.net/browse/QTY-1331)
Add the ability to add a due date offset for the last assignment in a course. 
Added UI element behind a launch darkly feature flag to `Account` settings page to allow users to update the offset for `Last Assigment Due`.  
Updates `scheduler.rb` to account for the offset using helper methods. When a new `Scheduler` is initialized by a call to `distribute_due_dates`, the `@enddate` is set by calling the `last_due_date` method. 
`last_due_date` now performs its arithmetic using the `Calendar` helper method `subtract_business_days` and the helper method `last_assignment_due_offset` which retrieves the setting for the account. All offset math is performed accounting for business days and holidays that are stored as a setting for the …

QTY-1331: Last Assignment due date field

---

app/assets/javascripts/canvas_shim/account_settings.js
app/assets/javascripts/canvas_shim/application.js.erb
app/assets/javascripts/canvas_shim/course_settings.js
app/decorators/controllers/accounts_controller_decorator.rb
app/decorators/controllers/context_modules_controller_decorator.rb
app/decorators/controllers/courses_controller_decorator.rb
app/decorators/models/account_decorator.rb
app/decorators/models/assignment_decorator.rb
app/decorators/models/assignment_group_decorator.rb
app/decorators/models/content_migration_decorator.rb
app/decorators/models/content_tag_decorator.rb
app/decorators/models/context_module_decorator.rb
app/decorators/models/context_module_progression_decorator.rb
app/decorators/models/course_decorator.rb
app/services/requirements_service.rb
app/services/requirements_service/commands/add_unit_item_with_min_score.rb
app/services/requirements_service/commands/apply_unit_exam_min_scores.rb
app/services/requirements_service/commands/reset_requirements.rb
app/services/requirements_service/commands/set_passing_threshold.rb
app/services/requirements_service/commands/set_school_thresholds_on_course.rb
app/services/requirements_service/queries/get_passing_threshold.rb
app/services/settings_service/repository_base.rb
app/views/accounts/_assignment_groups_thresholds.html.erb
app/views/accounts/settings.html.erb
spec/models/content_migration_spec.rb
spec/services/pipeline_service/serializers/course_spec.rb
spec/services/requirements_service/add_unit_item_with_min_score_spec.rb
spec/services/requirements_service/set_passing_threshold_spec.rb
spec/services/requirements_service_spec.rb
spec/support/examples/stubbed_network_context.rb

[QTY-1355](https://strongmind.atlassian.net/browse/QTY-1355)
Allow school personnel to set a school wide default minimum threshold at the account level that is reflected on all new and currently created (but not yet started) courses by assignment group. 
Update account settings page to have fields for a pre-determined set of assignment groups, replacing the existing threshold fields for assignments and exams. 
Adds `AssignmentGroup::GROUP_NAMES` constant to hold the assignment groups for which we will support adding default thresholds. 
Utilizes the existing `RequirementsService` and `SettingsService` to dynamically get and set thresholds for the supported assignment groups. 
Adds callbacks to `assignment_decorator.rb` and `content_migration_decorator.rb` as well as delayed jobs in …

QTY-1355: Add assignment group passing thresholds to account settings

---

app/assets/javascripts/canvas_shim/course_settings.js
app/decorators/controllers/accounts_controller_decorator.rb
app/decorators/controllers/context_modules_controller_decorator.rb
app/decorators/controllers/courses_controller_decorator.rb
app/decorators/models/account_decorator.rb
app/decorators/models/assignment_group_decorator.rb
app/decorators/models/context_module_decorator.rb
app/decorators/models/course_decorator.rb
app/services/pipeline_service/serializers/course.rb
app/services/requirements_service.rb
app/services/requirements_service/commands/apply_assignment_group_min_scores.rb
app/services/requirements_service/commands/force_min_scores.rb
app/services/requirements_service/commands/reset_requirements.rb
app/services/requirements_service/commands/set_school_thresholds_on_course.rb
app/views/courses/_assignment_groups_thresholds.html.erb
app/views/courses/settings.html.erb
spec/models/context_module_spec.rb
spec/services/pipeline_service/serializers/course_spec.rb
spec/services/requirements_service/reset_requirements_spec.rb
spec/services/requirements_service_spec.rb
spec/support/factories.rb

[QTY-1599](https://strongmind.atlassian.net/browse/QTY-1599)
Allow school personnel to set passing thresholds at the course-level, which take precedence over the account-level passing thresholds (added by [this PR](https://github.com/StrongMind/canvas_shim/pull/412)), if set. 
Update course settings page to have fields for a pre-determined set of assignment groups, replacing the existing threshold fields for assignments and exams.
Utilize AssignmentGroup::GROUP_NAMES constant added by the previous PR to determine which assignment groups we will support passing thresholds for by default.
Utilizes the existing RequirementsService and SettingsService to dynamically get and set thresholds for the supported assignment groups.
Updates the checks in `context_modules_controller_decorator.rb` to …

QTY-1599: Add Threshold settings for all assignment groups at the course level

---

app/decorators/controllers/courses_controller_decorator.rb

Co-authored-by: Angel Diaz <angel.diaz@strongmind.com>
- Check for context before requirements service call to get passing thresholds for course
- Check for passing thresholds before attempting to set js_env
Following a recent deployment, we saw a large number for Sentry errors coming due to a nil Object error. This change aims to silence those exceptions. 
This change adds a checks for `@context` and `passing_thresholds` existence before attempting to call the `RequirementsService` and subsequently add the resulting thresholds into `js_env`
Verified the affected page, `Courses#show`, still loads as expected locally and in production and no new Sentry errors appeared when hitting the affected routes.

QTY-passing-thresholds-nil-object-fix

---

.github/workflows/rspec.yml

[QTY-1741]()
looks like we we're installing the latest version of bundler in the github actions test box, version locked it to mach our gemfile
updated rspec.yml
manually run rpsec github action
[QTY-1741]: https://strongmind.atlassian.net/browse/QTY-1741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

QTY-1741: update rpsec.yml to install bundler 2.3.25

---

app/decorators/models/submission_decorator.rb
app/services/alerts_service/alerts/guided_practice_submitted.rb
spec/decorators/models/submission_spec.rb
spec/models/assignment_spec.rb
spec/models/course_progress_spec.rb
spec/models/student_enrollment_spec.rb
spec/models/submission_comment_spec.rb
spec/models/submission_spec.rb
spec/services/alerts_service/alerts/guided_practice_submitted_spec.rb
spec/services/assignments_service/commands/set_enrollment_assignment_due_dates_spec.rb
spec/services/grades_service/queries/zero_grader_submissions_spec.rb
spec/services/pipeline_service/V2/nouns/submission_spec.rb
spec/services/pipeline_service/V2/payload_spec.rb
spec/services/pipeline_service/models/noun_spec.rb
spec/services/pipeline_service/serializers/submission_spec.rb
spec/services/pipeline_service/serializers/unit_grades_spec.rb
spec/services/units_service/commands/get_unit_grades_spec.rb
spec/services/units_service/queries/get_submissions_spec.rb
spec/support/factories.rb

[QTY-1459](https://strongmind.atlassian.net/browse/QTY-1459)
Teachers would like to be alerted when a student submits a Guided Practice to be graded.
As the alerts foundation has already been laid out, our strategy was to build upon that foundation. We created the alert attributes, then utilized the submission_decorator to add our logic to have the AlertsService::Client create our alert. We configured the alert to be sent when it is the proper Assignment Group name of 'Guided Practice', and also checked to make sure that it was submitted. 
- Create a course
- Have a teacher and a student both apart of that course
- Have the student submit an assignment that is apart of the 'Guided Practice' Assignment Group
- Verify that the teacher has received an alert of submission on their dashboard. …

QTY-1459 Create alert for when a Guided Practice is submitted

---

app/decorators/models/discussion_topic/materialized_view_decorator.rb
app/decorators/models/discussion_topic_decorator.rb
app/decorators/models/materialized_view_decorator.rb
spec/test_app/app/models/discussion_topic/materialized_view.rb

[QTY-1504](https://strongmind.atlassian.net/browse/QTY-1504)
Discussion topics have an optional setting that prevents students from viewing posts until they have contributed to the thread. Before this change, students were bypassing this by posting garbage values as a post, viewing other student's posts, and cheating off of their peers. To prevent cheating, we've updated this setting to not only require students to contribute, but to receive a grade for their post, before they can view their peer's contributions (this sits behind a launch darkly flag).
We extended the **materialized_view.rb** by adding a decorator **materialized_view_decorator.rb** which will prevent posts from rendering unless the student viewing the discussion topic has posted and that post has been graded. These checks …

QTY-1504 prevent cheating for graded discussion topics when user must post before viewing all posts

---

app/services/pipeline_service/V2/api/publish.rb

[QTY-2067](https://strongmind.atlassian.net/browse/QTY-2067)
When working in our development environment, we are receiving errors regarding making calls to the pipeline service. As we typically don't utilize the pipeline service in our dev environment, turning off the setting will alleviate this issue.
The logic was already partially implemented throughout Canvas. We just needed to complete it by changing the setting and utilize Rails cache to make the calls vs. calling the db.
Create a course while watching your logs, the error should no longer appear. In addition, tested on newidsandbox and it is still working as expected.
[QTY-2067]: https://strongmind.atlassian.net/browse/QTY-2067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

QTY-2067: Remove pipeline service calls when in development

---

app/decorators/controllers/accounts_controller_decorator.rb
app/views/accounts/settings.html.erb

[QTY-3926](https://strongmind.atlassian.net/browse/QTY-3926)
This pr removes the feature flag for exposing default course access times to partners. this feature is being released and no longer needs to be gated behind a flag
remove the flag and the one reference to the flag on the front end.
n/a
n/a
[QTY-3926]: https://strongmind.atlassian.net/browse/QTY-3926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(S) QTY-3926: remove feature flag for expose_default_course_access_times

---

app/decorators/controllers/accounts_controller_decorator.rb
app/views/accounts/settings.html.erb

expose-first-and-last-assignment-due-date-field: this feature has been fully released and no longer required the flag
[QTY-3927](https://strongmind.atlassian.net/browse/QTY-3927)
expose-first-and-last-assignment-due-date-field: this feature has been fully released and no longer required the flag
remove references to flag
will deploy & test on new-id-sandbox
n/a
[QTY-3927]: https://strongmind.atlassian.net/browse/QTY-3927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(B) QTY-3927: remove reference to feature flag

---

app/services/pipeline_service/api/publish.rb
spec/services/pipeline_service/api/publish_spec.rb

currently we only know that a Noun fails validation...but we don't know why. this extra info in the exception should help.
[QTY-4054](https://strongmind.atlassian.net/browse/QTY-4054)
This pr adds some extra info to the exception loggin when a noun fails validation during a publish to the data pipeline.
Adding object.errors.full_messages should give us access to any errors that pop up when we call valid? on the object
n/a
n/a
[QTY-4054]: https://strongmind.atlassian.net/browse/QTY-4054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(B) QTY-4054: add any validation errors to exception message

---

app/decorators/lib/delayed/work_queue/parent_process/server.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-1475)
So that we can autoscale the number of workers, we need to be able to see the number of idle workers and remaining jobs.
Because the original check_for_work method does this when DEBUG logging when checking for work, and there are no other debug logs in the method, wrap the original method and set the log level to debug temporarily.
See https://github.com/instructure/inst-jobs/blame/e3a9feecb43fd9d7dac02623a6de806f97b576ab/lib/delayed/work_queue/parent_process/server.rb#L99
Tested in new-id-sandbox

BEL-1475 Log number of remaining jobs and idle workers in queue for autoscaling

---

app/decorators/controllers/accounts_controller_decorator.rb
app/decorators/models/course_decorator.rb

[QTY-4491](https://strongmind.atlassian.net/browse/QTY-4491)
Bug: courses created from powerschool to canvas were coming in with incorrect course start/end times even when the account setting was set.
Add a timezone setting since system setting is always UTC. Append this timezone to the existing start time and end time settings. Remove DateTime.parse because this creates an offset on the date (causes multiple offsets to happen). If we allow the course to create itself using the start/end time directly, it automatically adjusts itself to the system timezone
In other words, setting start_at of a course to the start time in the setting:
`course.start_at = "12:00 AM MST"`
Automatically translates to this in the DB:
`start_at: "2023-09-14 07:00:00"`
Test locally in the rails console
Deploy to …

QTY-4491 add timezone setting, include it on start/end time setting, and remove DateTime.parse

---

app/views/context_modules/_module_item_next.html.erb

[QTY-4252](https://strongmind.atlassian.net/browse/QTY-4252)
This is part of a fix for a bug that happens when a new module item is created and then the user tries to go to the item (before this fix, the user gets a "page not found" error).
This particular change is needed to fix element properties and ensure that module item URLs are assigned properly.
The `assignment_id` property is set to a value that relies on some conditional logic on `module_item`. For new items, `module_item` comes through as nil and therefore the property following `assignment_id` becomes the value of `assignment_id`.
i.e.
This code would have `some_conditional_logic` which would return nil:
```
assignment_id = <%= some_conditional_logic %>
href = "some_url"
```
Which would generate the element like this:
``` …
```

QTY-4252 add safeguarding for when module_item is nil, ensure element properties are formatted correctly

---

app/decorators/models/course_decorator.rb

the current implementation was setting start/end dates incorrectly
[QTY-4975](https://strongmind.atlassian.net/browse/QTY-4975)
this pr re-implements the set_course_start_end_time_from_school, we refactored this method to be more verbose and not use the send method.
undo the meta programming implementation into more verbose logic
we were able to replicate this in a rails console, once we refactored we monkey patched in the console to verify things were working correctly
n/a
[QTY-4975]: https://strongmind.atlassian.net/browse/QTY-4975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(B) QTY-4975: refactor set_course_start_end_time_from_school

---

app/decorators/models/course_decorator.rb

course_start_time_from_school and course_end_time_from_school
this should prevent timezone issues
[QTY-4997](https://strongmind.atlassian.net/browse/QTY-4997)
fix an issue with timezones interfering when calling Datetime.parse & Datetime.new in the course_decorators before_create callback, set_course_start_end_time_from_school
remove the datetime.parse .new and manipulate the start end times directly
rpsec
n/a
[QTY-4997]: https://strongmind.atlassian.net/browse/QTY-4997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(S) QTY-4997: remove Datetime.parse & Datetime.new from

---

app/services/grades_service/commands/zero_out_assignment_grades.rb
spec/services/grades_service/commands/zero_out_assignment_grades_spec.rb

[QTY-6247](https://strongmind.atlassian.net/browse/QTY-6247)
explicitly call recompute_final_score on enrollment when zero grader grades an assignment
once the assignment is graded by zero grade, recompute_final_score will be called which should recompute the current scores and publish to the data pipeline
rspec. reset patricia morans grades for [chemistry](https://new-id-sandbox.strongmind.com/courses/1821), rerun autograder and see a student enrollment noun for each assignment that got graded
86 assignments autograded, 86 nouns published
[QTY-6247]: https://strongmind.atlassian.net/browse/QTY-6247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

QTY-6247: explicitly call recompute_final_score when autograder grades an assignment

---

app/services/pipeline_service/logger.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/TEAM-NUMBER)
An outage happened because an old echo service was removed, which was being used as a redundant logger for the data pipeline.
Remove the body of the class that was posting. We'll need to clear it out properly afterwards.
O'reilly.

QTY-6879 Remove redundant logging

---

app/assets/javascripts/canvas_shim/course_snapshot.js

[QTY-4765](https://strongmind.atlassian.net/browse/QTY-4765)
Progress bar column for course progress was not being sorted properly
Custom sort logic
Local Canvas VM testing
[QTY-4765]: https://strongmind.atlassian.net/browse/QTY-4765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(B) QTY-7327: Get sortable value off of html element

---

app/decorators/controllers/discussion_topics_controller_decorator.rb
app/decorators/controllers/users_controller_decorator.rb

[QTY-7013](https://strongmind.atlassian.net/browse/QTY-7013)
[QTY-7015](https://strongmind.atlassian.net/browse/QTY-7015)
Strongmind added code is not checking for user permissions before making data changes, this PR addresses that
Guard clauses to exit endpoints before doing data changes
Tested on canvas VM
Special programs needs to be tested on new_id_sandbox
[QTY-7013]: https://strongmind.atlassian.net/browse/QTY-7013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[QTY-7015]: https://strongmind.atlassian.net/browse/QTY-7015?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(B) QTY-7013 && QTY-7015: Address canvas vulnerabilities by adding authorization guard clauses

---

app/decorators/models/course_decorator.rb
spec/models/course_spec.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-8461)
Some courses have some incorrect start and end times. We believe we have a fix.
We need to take in a date and time, and return a combined date-time, while considering the time-zone of the inputed time.
We were originally not converting the time component into UTC properly.
Unit specs for the `#create` method on the `Course` model. This allows us to test the `set_course_start_end_time_from_school` method on a `before_create` callback.
We tested creating course #3863 in new-id-sandbox and confirmed that the times are now correct.

Fix time zone dates

---

app/decorators/models/course_decorator.rb
spec/models/course_spec.rb

* Refactor on parsing start/conclude_at dates.
* Account for when the months/years rollover - we were getting an exception [here](https://strongmind-4j.sentry.io/issues/5585679033/?project=6262567&referrer=jira_integration) because we are trying to add a day to January 31rst and it's exploding when trying to create a day for January 32nd. I added some specs and cases for when the months/years rollover in these cases.
* There do not need to be two separate functions for parsing start and conclude
dates. Now we can account for date rollovers in the case that the start time is
much later in the day.
* add `offset` num of days to the date as a whole, instead of adding and `offset` number to the count of days.
* Unit specs

refactor-rollover-dates

---

app/decorators/models/course_decorator.rb
spec/models/course_spec.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-8849)
Course Updates from one roster are causing times to ignore system time settings.
Apply a before_commit to check system time settings and change accordingly for a course.
Created new specs that consider the update path.
Ensured save path still works.

(B) QTY-8849: apply-date-time-fix-to-all-updates - Write tests and fix

---

app/decorators/models/course_decorator.rb
spec/models/course_spec.rb

- **(B) apply-date-time-fix-to-all-updates: Ensure start/end are persisted on save**
[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-8849)
We need to apply our fix for start/end to updates as well. The problem is we
were using an after_commit, meaning it wasn't being persisted.
Change the after_commit to a before_save.
We are now ensuring that the course is persisted before we test our expected
values.

Apply proper start/end on all saves

---

app/decorators/models/course_decorator.rb
app/views/courses/settings.html.erb
spec/models/course_spec.rb

[QTY-9035](https://strongmind.atlassian.net/browse/QTY-9035)
Course updates were causing course conclude dates to changes dates depending on their timezone.
Pass param in frontend to manually calculate timezones
Rspec, Local testing on teamviewer VM
[QTY-9035]: https://strongmind.atlassian.net/browse/QTY-9035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(B) QTY-9035: Changing callback to after create

---

app/decorators/lib/basic_lti/basic_outcomes_decorator.rb
db/migrate/20241114205608_add_published_grade_and_score_to_submission.rb
spec/lib/basic_lti/basic_outcomes/lti_response_spec.rb
spec/test_app/app/models/assignment.rb
spec/test_app/db/schema.rb
spec/test_app/lib/basic_lti/basic_outcomes.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/PLT-13623)
Learnosity Player is getting 504s due to grade passback in canvas being slow. We think this may be due to the "keep highest score" feature in the canvas shim. The implementation looped over every version to find the highest and parsed the YAML twice for each version. 
Rather than looping over versions, we are simply querying before we submit to see what the current submission score is. If the new score is higher, we do nothing. If the current score is lower, we update the score and grade columns to equal the previous score/grade.
Added new specs to verify actual functionality. Made the test app do a more realistic implementation of the create_homework_submission method.

PLT-13623: Reduce complexity of "keep highest score" feature to improve performance

---

app/decorators/models/course_decorator.rb
spec/models/course_spec.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-10001)
User's are experiencing a bug where times in MDT are being converted to MST.
Add MT as a custom timezone that maps to ActiveSupport, America/Denver.
Specs

Qty 10001: Add support for MT time by mapping to America/Denver

---

Gemfile.lock
app/decorators/models/course_decorator.rb
spec/models/course_spec.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-10001)
Times are not being stored correctly for areas that observe daylight savings
Include the date with the time when calculating UTC offset.  Use ActiveRecord to parse the date/time and calculate UTC offset instead of calculating manually.
Passes all specs in  course_spec.rb

(B) QTY-10001: Include date when determining UTC offset

---

app/decorators/models/assignment_decorator.rb
spec/models/assignment_spec.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-10125)
A submissions grade and score are not being set to nil when an assignment is excused for a user. This is causing the gradebook to not display 'EX'.
Update submission grade and score to nil when excused
Specs

(B) QTY-10125: Set grade and score to nil when submission is excused

---

app/decorators/lib/delayed/worker.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-3936)
Do not kill running work when we scale down workers.
In order to ensure our ECS scaling does not kill running jobs, we need to set task protection while workers are doing work.
We do this by sharing a mutex across all running threads, keeping a count of running jobs in the perform state. When the count gets to 0, unset protected status, and when it increments past 0, set protected status.
Tested on new-id-sandbox - imported cartridge and watched task protection status be turned on and off again.

BEL-3936 Ensure that ECS scaling will not kill running work

---

app/decorators/lib/delayed/worker.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-11338)
Stop hammering the ECS task protection API.
We're running up against task protection API limits due to quick bursts of many small tasks. In order to do this, we want to debounce unprotecting tasks and make sure we never double-send updates to task protection. We still, however want to protect a task as soon as we start one.
This is a first draft at doing this. I suspect we can simplify and make this more comprehensible.
In draft, not yet tested.

QTY-11338 First draft of debouncing task protection

---

app/decorators/models/course_progress_decorator.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-4804)
Fix timeouts that happen attempting to pass back grades from other systems. (And some other endpoints, also).
Tracing the timeout issues in this bug leads us to an N+1 that causes significant slowdowns in several endpoints. By preloading the content tags (and the content) we can avoid this.
Ran the unit test suite with Jothan and also confirmed that this code was covered and tested.

BEL-4804 fix timeout issues

---

app/decorators/models/course_progress_decorator.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-4804)
There were 3-4 levels of n+1 bugs in this section of code. Fixing 1 of them seems to get us to the point of not triggering the 55s timeout, but we stretch goaled this in.
Canvas forbids using .includes(), presumably because they prefer to always make the explicit choice of which behaviour is happening to improve performance, so we have to use preload or eager_load here.
We're choosing preload, because everything that is using this is close by, and that seems less confusing.
Unit testing in CI/CD

BEL-4804 Deal with second level of N+1s

---

app/views/courses/show.html.erb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-13258)
We need to replicate the exact contexts that are causing the slowdowns. We'll
wait for the next Sentry issue and be able to see some more info.

QTY-13258: Add extra context for slow course pages

---

app/decorators/models/course_decorator.rb
spec/models/course_spec.rb
spec/test_app/app/models/enrollment.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-13258)
Make course pages with many enrollments faster.
In a before action to set the online count for a course, we are iterating over every active enrollment for that course and setting stuff in redis. This slows down all course pages. Here, by doing redis fetches in batches of 1000, we've noticed an increase in page load times.
We spun up a new course added 6500 students, and made a ton of enrollments for them. We then sped up the page significantly by targeting `strongmind_badge_counts_for`, which is problematic.

QTY-13258: Do not query redis enrollment-no. of times

---

.github/workflows/rspec.yml

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-5319)
Ubuntu-20.04 hosted runner image is closing down
This pull request updates the GitHub Actions workflow configuration for running tests. The most important change is the update of the runner version to use the latest Ubuntu version.
Workflow configuration update:
* [`.github/workflows/rspec.yml`](diffhunk://#diff-1fadaba7942eb03a370984f465dc59789417e580083e4bcaa2d073959b1815beL16-R16): Changed the runner version from `ubuntu-20.04` to `ubuntu-latest` for the `test` job.

BEL-5319 Update github actions runner Ubuntu

---

app/services/grades_service/queries/zero_grader_submissions.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-14666)
Some submissions are being marked as submitted but aren't being graded and this is causing the autograder to not assign zeros to past due assignments.
Remove the workflow check of 'unsubmitted' from the zero out method of the autograder. There are no cases where a submission should have a submitted attribute but the score and the grade are both null. Therefore, if a submission is past its due date, is not exempt, the zero out setting is checked, and both the grade and score are nil, zero out the submission.

QTY-14666: Remove Submitted Check for Autograder

---

app/services/attendance_service/commands/check_lockout.rb
spec/services/attendance_service/commands/check_lockout_spec.rb
spec/support/examples/stubbed_network_context.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-14939)
For schools that do not use attendance lockouts, we are currently hitting the attendance API and getting a 404, triggering an exception to sentry and causing attendance API to do way more work than it should.
Fix this by checking for an env var ( ATTENDANCE_LOCKOUT_DISABLED ).
Manual testing + unit testing

(B) QTY-14939 Fix hammering attendance API

---

app/services/attendance_service/commands/check_lockout.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/PLT-16912)
https://strongmind-4j.sentry.io/issues/6360033685/
We are receiving over 100K Sentry issue related to our lockout service. The main offender is a internal user that doesn't not have any attendance.
Check for the user's integration and ID and return false (not locked out). This will reduce the Sentry errors by not returning a 404 and will lower the calls to our service by not checking on a user we know is not in the attendance system.
None
None

(B) PLT-16912 Exclude the Trans Check User from the lockout check.

---

app/decorators/models/course_decorator.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-17508)
When user update course setting without start and end time, it will throw a nil error.
Move save method to the next line to avoid early implicit return
Test to save/update course without start and end time

(B) QTY-17508: Fix course setting update issue on potential nil object
